
// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview An AI-powered bill splitting flow.
 *
 * - splitBill - A function that splits a bill based on a natural language description.
 * - BillSplitterInput - The input type for the splitBill function.
 * - BillSplitterOutput - The return type for the splitBill function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const BillSplitterInputSchema = z.object({
  description: z
    .string()
    .describe('A natural language description of the bill to be split, including people and items.'),
});
export type BillSplitterInput = z.infer<typeof BillSplitterInputSchema>;

const PersonSplitSchema = z.object({
    person: z.string().describe("The name of the person."),
    amount: z.number().describe("The amount this person owes."),
    items: z.array(z.string()).describe("The items this person is paying for.")
});

const BillSplitterOutputSchema = z.object({
  totalAmount: z.number().describe("The total amount of the bill."),
  splits: z
    .array(PersonSplitSchema)
    .describe('An array of objects, where each object represents one person\'s share of the bill.'),
});
export type BillSplitterOutput = z.infer<typeof BillSplitterOutputSchema>;

export async function splitBill(input: BillSplitterInput): Promise<BillSplitterOutput> {
  return billSplitterFlow(input);
}

const prompt = ai.definePrompt({
  name: 'billSplitterPrompt',
  input: {schema: BillSplitterInputSchema},
  output: {schema: BillSplitterOutputSchema},
  prompt: `You are an intelligent bill splitter. Your task is to analyze a description of a bill and split it among the people mentioned.

  Rules:
  1.  Identify all the people involved in the split.
  2.  Identify all the items and their costs.
  3.  If there are shared items, divide their cost equally among all people.
  4.  Calculate the total amount each person owes by summing their individual items and their share of any common items.
  5.  Calculate the grand total of the bill.
  6.  Return the result in the specified JSON format. Assume the user asking is one of the people if they use "me" or "I".

  Bill Description:
  {{{description}}}

  Generate the split breakdown.`,
});

const billSplitterFlow = ai.defineFlow(
  {
    name: 'billSplitterFlow',
    inputSchema: BillSplitterInputSchema,
    outputSchema: BillSplitterOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
