
// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview A simple financial chatbot.
 *
 * - chatWithBot - A function that provides a response to a user's financial question.
 * - ChatbotInput - The input type for the chatWithBot function.
 * - ChatbotOutput - The return type for the chatWithBot function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ChatbotInputSchema = z.object({
  userMessage: z.string().describe('The user\'s message to the chatbot.'),
});
export type ChatbotInput = z.infer<typeof ChatbotInputSchema>;

const ChatbotOutputSchema = z.object({
  answer: z
    .string()
    .describe('The chatbot\'s response to the user\'s message.'),
});
export type ChatbotOutput = z.infer<typeof ChatbotOutputSchema>;

export async function chatWithBot(input: ChatbotInput): Promise<ChatbotOutput> {
  return chatbotFlow(input);
}

const prompt = ai.definePrompt({
  name: 'chatbotPrompt',
  input: {schema: ChatbotInputSchema},
  output: {schema: ChatbotOutputSchema},
  prompt: `You are Echo, an AI Money Coach and "Smart Pocket Planner" for students. Your goal is to provide actionable financial plans, not just answers.

When a student tells you their financial situation (e.g., "I have ₹3,000 left for the month, I need to pay rent, eat, and also save ₹800 for a concert"), you MUST:

1.  **Create a Custom Spending Plan:** Break down their remaining money into a daily or weekly allowance.
2.  **Establish Goal Pots:** Explicitly mention that you are setting aside money for their stated goals (e.g., "I'm reserving a 'goal pot' of ₹800 for the concert.").
3.  **Suggest Micro-Hacks:** Provide at least two specific, actionable tips for saving money relevant to their situation (e.g., suggest cheaper food options, discount travel, splitting expenses).
4.  **Warn About Overspending:** Include a clear warning about what could happen if they overspend (e.g., "If you order Zomato today, you’ll miss your concert goal.").
5.  **Keep it Conversational:** Be friendly, encouraging, and use emojis to make the interaction engaging.

User's situation: {{{userMessage}}}

Generate a helpful and actionable plan.`, 
});

const chatbotFlow = ai.defineFlow(
  {
    name: 'chatbotFlow',
    inputSchema: ChatbotInputSchema,
    outputSchema: ChatbotOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
